<?xml version="1.0"?>

<robot name="checkpoint" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:arg name="mass" default="100" />
  <xacro:arg name="radius" default="0.75" />
  <xacro:arg name="thickness" default="0.05" />
  <xacro:arg name="altitude" default="1.5" />

  <xacro:property name="namespace" value="$(arg namespace)" />
  <xacro:property name="mass" value="$(arg mass)" />
  <xacro:property name="scale_r" value="${$(arg radius)/7.5}" />
  <xacro:property name="scale_t" value="${$(arg thickness)/50}" />
  <xacro:property name="pillar_length" value="${$(arg altitude)-0.1-$(arg radius)}" />
  <xacro:property name="mesh_file" value="package://rrc_control/models/mesh/Plain_Cylinder.stl" />

  <!-- Macro for the inertia of a box -->
  <xacro:macro name="box_inertia" params="x y z mass">
    <inertia ixx="${0.0833333 * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0"
      iyy="${0.0833333 * mass * (x*x + z*z)}" iyz="0.0"
      izz="${0.0833333 * mass * (x*x + y*y)}" />
  </xacro:macro>

  <!-- Macro for the inertia of a cylinder -->
  <xacro:macro name="cyl_inertia" params="h r mass">
    <inertia ixx="${0.0833333 * mass * (3*r*r + h*h)}" ixy="0.0" ixz="0.0"
      iyy="${0.0833333 * mass * (3*r*r + h*h)}" iyz="0.0"
      izz="${0.5 * mass * (r*r)}" />
  </xacro:macro>

    <!-- Macro for the inertial properties of a box -->
  <xacro:macro name="box_inertial" params="x y z mass *origin">
    <inertial>
      <mass value="${mass}"/>
      <xacro:insert_block name="origin" />
      <xacro:box_inertia x="${x}" y="${y}" z="${z}" mass="${mass}" />
    </inertial>
  </xacro:macro>




<link name="ring">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
      <mesh filename="${mesh_file}" scale="${scale_r} ${scale_r} ${scale_t}" />
    </geometry>
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="${pi} 0 0" />
    <geometry>
      <mesh filename="${mesh_file}" scale="${scale_r} ${scale_r} ${scale_t}" />
     </geometry>
  </collision>
  <inertial>
    <mass value="2" />
    <xacro:cyl_inertia h="${50*scale_t}" r="${7.5*scale_r}" mass="2" />
  </inertial>
</link>

</robot>