<?xml version="1.0" ?>
<robot name="turtlebot3_burger" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find turtlebot3_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find turtlebot3_description)/urdf/turtlebot3_burger.gazebo.xacro"/>
  <xacro:property name="radius" default="0.002" />
  <xacro:property name="pillar_length" value="0.08" />
  <xacro:property name="mass" value="$(arg mass)" />

  <!-- Macro for the inertia of a cylinder -->
  <xacro:macro name="cyl_inertia" params="h r mass">
    <inertia ixx="${0.0833333 * mass * (3*r*r + h*h)}" ixy="0.0" ixz="0.0"
      iyy="${0.0833333 * mass * (3*r*r + h*h)}" iyz="0.0"
      izz="${0.5 * mass * (r*r)}" />
  </xacro:macro>

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.010" rpy="0 0 0"/>
  </joint>


  <joint name="base_to_fl_pillar" type="fixed">
    <origin xyz="0.03 0.03 ${(pillar_length/2) + 0.14}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="front_left_pillar" />
  </joint>


  <link name="front_left_pillar">
      <visual>
        <geometry>
          <cylinder length="${pillar_length}" radius="${radius}"/>
        </geometry>
        <material name="blue">
          <color rgba="0 0 0.8 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${pillar_length}" radius="${radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <xacro:cyl_inertia h="${pillar_length}" r="${radius}" mass="0.1"/>
      </inertial>
  </link>

  <joint name="base_to_fr_pillar" type="fixed">
    <origin xyz="0.03 -0.03 ${(pillar_length/2) + 0.14}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="front_right_pillar" />
  </joint>


  <link name="front_right_pillar">
      <visual>
        <geometry>
          <cylinder length="${pillar_length}" radius="${radius}"/>
        </geometry>
        <material name="blue">
          <color rgba="0 0 0.8 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${pillar_length}" radius="${radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <xacro:cyl_inertia h="${pillar_length}" r="${radius}" mass="0.1"/>
      </inertial>
  </link>

  <joint name="base_to_br_pillar" type="fixed">
    <origin xyz="-0.09 -0.03 ${(pillar_length/2) + 0.14}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="back_right_pillar" />
  </joint>


  <link name="back_right_pillar">
      <visual>
        <geometry>
          <cylinder length="${pillar_length}" radius="${radius}"/>
        </geometry>
        <material name="blue">
          <color rgba="0 0 0.8 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${pillar_length}" radius="${radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <xacro:cyl_inertia h="${pillar_length}" r="${radius}" mass="0.1"/>
      </inertial>
  </link>

  <joint name="base_to_bl_pillar" type="fixed">
    <origin xyz="-0.09 0.03 ${(pillar_length/2) + 0.14}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="back_left_pillar" />
  </joint>


  <link name="back_left_pillar">
      <visual>
        <geometry>
          <cylinder length="${pillar_length}" radius="${radius}"/>
        </geometry>
        <material name="blue">
          <color rgba="0 0 0.8 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${pillar_length}" radius="${radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <xacro:cyl_inertia h="${pillar_length}" r="${radius}" mass="0.1"/>
      </inertial>
  </link>


  <joint name="base_to_disc" type="fixed">
    <origin xyz="-0.03 0.0 ${(pillar_length) + 0.14}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="disc" />
  </joint>


  <link name="disc">
      <visual>
        <geometry>
          <cylinder length="0.005" radius="0.08"/>
        </geometry>
        <material name="lightgrey">
          <color rgba="0.95 0.9 0.9 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.005" radius="0.08"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <xacro:cyl_inertia h="0.005" r="0.08" mass="0.1"/>
      </inertial>
  </link>



  <link name="base_link">
    <visual>
      <origin xyz="-0.032 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/bases/burger_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <origin xyz="-0.032 0 0.070" rpy="0 0 0"/>
      <geometry>
        <box size="0.140 0.140 0.143"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="8.2573504e-01"/>
      <inertia ixx="2.2124416e-03" ixy="-1.2294101e-05" ixz="3.4938785e-05"
               iyy="2.1193702e-03" iyz="-5.0120904e-06"
               izz="2.0064271e-03" />
    </inertial>
  </link>

  <joint name="wheel_left_joint" type="fixed">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.0 0.08 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/wheels/left_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="wheel_right_joint" type="fixed">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.0 -0.080 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/wheels/right_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="caster_back_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_link"/>
    <origin xyz="-0.081 0 -0.004" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="-0.032 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="-0.032 0 0.172" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.0315" radius="0.055"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>


  <link name="constraint">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://ss_workshop/models/meshes/expParaboloid.stl" scale="1.0 1.0 1.0"/>
      </geometry>
      <material name="redTransparent">
        <color rgba="0.8 0 0.0 0.4"/>
      </material>
    </visual>    
  </link>

  <link name="safety_disc">
      <visual>
        <geometry>
          <cylinder length="0.005" radius="0.32"/>
        </geometry>
        <material name="greyTransparent">
          <color rgba="0.8 0.8 0.8 0.3"/>
        </material>
      </visual>
  </link>


  <joint name="base_to_safety_disc" type="fixed">
    <origin xyz="-0.03 0.0 0.0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="safety_disc" />
  </joint>


  <joint name="constraint_joint" type="fixed">
    <parent link="disc"/>
    <child link="constraint"/>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
  </joint>

  <gazebo reference="constraint">
    <material>Gazebo/RedTransparent</material>
  </gazebo> 

</robot>
